name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+2
  rxdart: ^0.23.1
  flutter_local_notifications:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  e2e: ^0.2.4+2
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

