name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: none

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.1.3
  flutter:
    sdk: flutter
  flutter_local_notifications:
    path: ../
  flutter_native_timezone: ^2.0.0
  http: ^0.13.4
  image: ^3.0.8
  path_provider: ^2.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# The following overrides exist to ensure the example app builds with the latest code
# of these packages as part of CI
dependency_overrides:
  flutter_local_notifications_linux:
    path: ../../flutter_local_notifications_linux
  flutter_local_notifications_platform_interface:
    path: ../../flutter_local_notifications_platform_interface

flutter:
  uses-material-design: true
  assets:
    - icons/
    - sound/

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"
