name: flutter_local_notifications
description: A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
version: 0.8.4
author: Michael Bui <michael@dexterx.dev>
homepage: https://github.com/MaikuB/flutter_local_notifications

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  platform: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0


# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.dexterous.flutterlocalnotifications
    pluginClass: FlutterLocalNotificationsPlugin


environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"