name: flutter_local_notifications
description: A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
version: 0.3.4
author: Michael Bui <maikub84@gmail.com>
homepage: https://github.com/MaikuB/flutter_local_notifications

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.4
  platform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^2.2.3


# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.dexterous.flutterlocalnotifications
    pluginClass: FlutterLocalNotificationsPlugin


environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"