name: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin
version: 4.0.0-dev.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications

dependencies:
  dbus: ^0.7.8
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^7.0.0-dev.1
  path: ^1.8.0
  xdg_directories: ">=0.2.0+1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
