name: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin
version: 6.0.0-dev.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications

flutter:
  plugin:
    implements: flutter_local_notifications
    platforms:
      linux:
        dartPluginClass: LinuxFlutterLocalNotificationsPlugin


dependencies:
  dbus: ^0.7.8
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^8.1.0-dev.1
  path: ^1.8.0
  xdg_directories: ">=0.2.0+1 <2.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"
