name: flutter_local_notifications_linux
description: Linux implementation of the flutter_local_notifications plugin
version: 0.1.0
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^4.0.0
  dbus: ^0.5.0
  path: ^1.8.0
  posix: ^2.1.0
  xdg_directories: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"
