name: flutter_local_notifications
description: A cross platform plugin for displaying and scheduling local
  notifications for Flutter applications with the ability to customise for each
  platform.
version: 18.0.0
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications
issue_tracker: https://github.com/MaikuB/flutter_local_notifications/issues

dependencies:
  clock: ^1.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications_linux: ^5.0.0
  flutter_local_notifications_platform_interface: ^8.0.0
  timezone: ">=0.9.0 <0.11.0"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dexterous.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
        dartPluginClass: AndroidFlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin
        dartPluginClass: IOSFlutterLocalNotificationsPlugin
      macos:
        pluginClass: FlutterLocalNotificationsPlugin
        dartPluginClass: MacOSFlutterLocalNotificationsPlugin
      linux:
        default_package: flutter_local_notifications_linux

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"
