name: flutter_local_notifications
description: A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
version: 3.0.1+3
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications

dependencies:
  flutter:
    sdk: flutter
  platform: ">=2.0.0 <4.0.0"
  flutter_local_notifications_platform_interface: ^2.0.0
  timezone: ^0.5.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.dexterous.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin
      macos:
        pluginClass: FlutterLocalNotificationsPlugin


environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"