name: flutter_local_notifications
description: A cross platform plugin for displaying and scheduling local
  notifications for Flutter applications with the ability to customise for each
  platform.
version: 8.1.1+2
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^4.0.1
  platform: ^3.0.0
  timezone: ^0.8.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dexterous.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin
      macos:
        pluginClass: FlutterLocalNotificationsPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.2.0'
