name: flutter_local_notifications_platform_interface
description: A common platform interface for the flutter_local_notifications plugin.
version: 9.0.0-dev.1
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_platform_interface
issue_tracker: https://github.com/MaikuB/flutter_local_notifications/issues

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
